### ISSUE TITLE
Redigir os fluxos principais de 3 casos de uso significativos para o negócio.

### ISSUE THREAD

**Issue by tmsasaki** [guqueiroz/ppads-projeto-05j-2018s2#1]

**Comment by guqueiroz** [comment]
**Caso de uso: Cadastro de usuário**
Fluxo principal
1- Usuário seleciona no menu a opção "Contatos"
2- Usuário seleciona a opção "Cadastrar novo contato"
3- Usuário preenche as informações desejadas
4- Usuário clica em salvar
5- É exibida para o usuário a mensagem "Contato cadastrado com sucesso"
6- Contato é cadastrado com sucesso no sistema

**Caso de uso: Favoritar contato**
Fluxo principal
1- Usuário seleciona no menu a opção "Contatos"
2- Usuário clica no ícone de favorito ao lado do contato
3- É exibida para o usuário a mensagem "Contato favoritado com sucesso"
4- Contato passa a ser exibido na lista de favoritos

**Caso de uso: Cadastrar evento**
Fluxo principal
1- Usuário seleciona no menu a opção "Calendário"
2- Usuário seleciona a opção "Adicionar evento"
3- Usuário adiciona novo evento e atribui à data desejada
4- Usuário em salvar
5- É exibida para o usuário a mensagem "Evento cadastrado com sucesso"
6- Evento criado passa a ser exibido no menu "Calendário"
