### ISSUE TITLE
Selecionar um caso de uso para ser implementado na SPRINT 1. Redigir os fluxos alternativos do caso de uso selecionado.

### ISSUE THREAD

**Issue by tmsasaki** [guqueiroz/ppads-projeto-05j-2018s2#2]

**Comment by guqueiroz** [comment]
**Caso de uso que será implementado na Sprint 1: Cadastrar contato**
**Fluxos alternativos:**
1- Cadastrar usuário que não possui telefone fixo
2- Cadastrar usuário que não possui e-mail
3- Cadastrar usuário sem preencher todas as informações obrigatórias
4- Concluir cadastro do usuário a partir da função editar
5- Cadastrar contato repetido com telefone de contato diferente
