### ISSUE TITLE
Desenvolver e implantar a aplicação com as funcionalidades do caso de uso da SPRINT 1.

### ISSUE THREAD

**Issue by tmsasaki** [guqueiroz/ppads-projeto-05j-2018s2#4]

**Comment by tmsasaki** [comment]
Última oportunidade para apresentar o resultado da SPRINT 1: 26 de outubro.

**Comment by guqueiroz** [comment]
SPRINT 1 

http://agenda-env.sxzbdfitxy.us-east-2.elasticbeanstalk.com/agenda.xhtml

**Comment by tmsasaki** [comment]
Criar uma pasta com o nome **src** e gravar nela o código-fonte.
