### ISSUE TITLE
Implementar todas as funcionalidades para a SPRINT FINAL.

### ISSUE THREAD

**Issue by tmsasaki** [guqueiroz/ppads-projeto-05j-2018s2#6]

**Comment by guqueiroz** [comment]
Link para acesso da aplicação: http://ec2-18-218-23-230.us-east-2.compute.amazonaws.com/agenda.xhtml

**Comment by tmsasaki** [comment]
Apresentação parcial para 30/11.
Apresentação final tardia para 07/11.

**Comment by guqueiroz** [comment]
Link para acesso à aplicação: http://agenda-env.sxzbdfitxy.us-east-2.elasticbeanstalk.com/agenda.xhtml

**Comment by guqueiroz** [comment]
Link para acesso à aplicação final: http://agenda-env.sxzbdfitxy.us-east-2.elasticbeanstalk.com/agenda.xhtml
