### ISSUE TITLE
Elaborar um DIAGRAMA DE IMPLANTAÇÃO (DEPLOYMENT DIAGRAM) da solução.

### ISSUE THREAD

**Issue by tmsasaki** [guqueiroz/ppads-projeto-05j-2018s2#7]
Dica: procurar por DEPLOYMENT DIAGRAM UML para ver alguns exemplos.

**Comment by guqueiroz** [comment]
![image](https://user-images.githubusercontent.com/28732807/48928514-e522d280-eec6-11e8-9fb1-f1a406c6670a.png)

**Comment by tmsasaki** [comment]
Colocar o diagrama na pasta docs.

Substituir o item "MÁQUINA VIRTUAL" por "TOMCAT"

**Comment by guqueiroz** [comment]
![diagramadeimplantacao](https://user-images.githubusercontent.com/28732807/49339329-27f74f80-f617-11e8-9b0c-6b81423889f1.png)

**Comment by guqueiroz** [comment]
![diagramadeimplantacao](https://user-images.githubusercontent.com/28732807/49483731-75440e80-f81b-11e8-8345-62a2ef832275.png)
